In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#loading the dataset
data=pd.read_csv("kenya_primary_schools_updated.csv")
data.head()

,FID,Name_of_Sc,Level_,Status,SchSponsor,Type1,Type2,Type3,PupilTeach,ClassrmRat,...,NoTeaching,NonTeachin,Province,District,Division,Location,Costituenc,Latitude,Longitude,Total Teachers
0,10001,CHEBIREBEI PRI,PRIMARY SCHOOL,PUBLIC,RELIGIOUS ORGANIZATION,MIXED,DAY ONLY,ORDINARY,15.7,5.9,...,0.0,0.0,RIFT VALLEY,KOIBATEK,KISANANA,MOGOTIO,SINENDE,0.27,36.14,9
1,10002,WASEGES PRI,PRIMARY SCHOOL,PUBLIC,RELIGIOUS ORGANIZATION,MIXED,DAY ONLY,ORDINARY,24.5,18.4,...,1.0,1.0,RIFT VALLEY,KOIBATEK,KISANANA,MOGOTIO,SINENDE,0.26,36.17,6
2,10003,KIRIBOT PRI,PRIMARY SCHOOL,PUBLIC,COMMUNITY,MIXED,DAY ONLY,ORDINARY,23.6,14.8,...,1.0,1.0,RIFT VALLEY,KOIBATEK,KISANANA,MOGOTIO,KABUSWO,0.24,36.18,15
3,10004,KABUSWO PRI SCH,PRIMARY SCHOOL,PUBLIC,COMMUNITY,MIXED,DAY ONLY,ORDINARY,33.3,29.6,...,2.0,0.0,RIFT VALLEY,KOIBATEK,KISANANA,MOGOTIO,KABUSWO,0.21,36.19,13
4,10005,VONDENI PRI SCHOOL,PRIMARY SCHOOL,PUBLIC,COMMUNITY,MIXED,DAY ONLY,ORDINARY,31.8,23.1,...,1.0,1.0,EASTERN,MACHAKOS,MASINGA,KIVAA,MASINGA,-0.88,37.70,10

In [4]:
#null values
data.isna().count()

FID               31230
Name_of_Sc        31230
Level_            31230
Status            31230
SchSponsor        31230
Type1             31230
Type2             31230
Type3             31230
PupilTeach        31230
ClassrmRat        31230
ToiletRati        31230
No_Classrm        31230
BoysToilet        31230
GirlsToilet       31230
TeachersTo        31230
TotalToile        31230
TotalBoys         31230
TotalGirls        31230
TotalEnrol        31230
GO_KTSC_M         31230
GOK_TSC_F         31230
authorityM        31230
authorityF        31230
PTA_BOG_M         31230
PTA_BOG_F         31230
OthersM           31230
OthersF           31230
NoTeaching        31230
NonTeachin        31230
Province          31230
District          31230
Division          31230
Location          31230
Costituenc        31230
Latitude          31230
Longitude         31230
Total Teachers    31230
dtype: int64

In [5]:
#trying to spot outliers.
data=data.rename(columns={"Total Teachers" : "Total_Teachers"})

q1=data["Total_Teachers"].quantile(0.25)
q3=data["Total_Teachers"].quantile(0.75)
iqr=q3-q1
print(iqr)
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

6.0

In [6]:
outliers = data[(data["Total_Teachers"] < lower_bound) | (data["Total_Teachers"] > upper_bound)]

print("Number of outliers:", outliers.shape[0])
outliers[["Name_of_Sc", "TotalEnrol", "Total_Teachers"]].head()

Number of outliers: 0

Empty DataFrame
Columns: [Name_of_Sc, TotalEnrol, Total_Teachers]
Index: []

In [7]:
#identifying null values
data.isnull()

,FID,Name_of_Sc,Level_,Status,SchSponsor,Type1,Type2,Type3,PupilTeach,ClassrmRat,...,NoTeaching,NonTeachin,Province,District,Division,Location,Costituenc,Latitude,Longitude,Total_Teachers
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31225,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31226,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31227,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31228,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31229,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
data.isnull()

,FID,Name_of_Sc,Level_,Status,SchSponsor,Type1,Type2,Type3,PupilTeach,ClassrmRat,...,NoTeaching,NonTeachin,Province,District,Division,Location,Costituenc,Latitude,Longitude,Total_Teachers
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31225,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31226,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31227,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31228,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31229,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
data.describe()

,FID,PupilTeach,ClassrmRat,ToiletRati,No_Classrm,BoysToilet,GirlsToilet,TeachersTo,TotalToile,TotalBoys,...,authorityF,PTA_BOG_M,PTA_BOG_F,OthersM,OthersF,NoTeaching,NonTeachin,Latitude,Longitude,Total_Teachers
count,31230.00000,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,...,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,31229.000000,31230.000000
mean,15615.50000,31.162045,30.516667,34.776230,8.973710,4.563739,5.101444,1.907298,0.258958,6.361587,...,0.019405,0.543245,0.455922,0.651766,0.683948,1.406993,0.858145,-0.608362,36.525356,8.987768
std,9015.46879,24.833860,21.666361,33.623305,5.251853,4.029990,4.791238,1.492698,2.509204,49.655488,...,0.317715,1.295726,1.223078,2.083962,2.068419,1.795247,2.389009,1.200369,1.549542,3.756925
min,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.660000,33.930000,3.000000
25%,7808.25000,16.300000,17.300000,16.100000,7.000000,2.000000,2.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,-1.230000,35.010000,6.000000
50%,15615.50000,30.400000,29.600000,28.000000,8.000000,4.000000,4.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,-0.560000,36.810000,9.000000
75%,23422.75000,42.100000,40.800000,44.000000,11.000000,6.000000,7.000000,2.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.090000,37.660000,12.000000
max,31230.00000,839.000000,839.000000,741.500000,121.000000,55.000000,196.000000,45.000000,58.000000,1233.000000,...,27.000000,22.000000,52.000000,51.000000,46.000000,41.000000,218.000000,5.290000,41.890000,15.000000

In [10]:
#	Districts with highest teacher shortages 
low_staff_per_district = data.groupby("District") ["Total_Teachers"].sum().sort_values(ascending=False).reset_index()
low_staff_per_district.head(10)

       District  Total_Teachers
0      MACHAKOS           16832
1       MAKUENI           16043
2         KITUI           12122
3       NAIROBI           11134
4  MERU CENTRAL            8902
5        NAKURU            8327
6    MERU NORTH            7629
7        MWINGI            7425
8   UASIN GISHU            7120
9       BUNGOMA            6647

In [11]:
top10_districts_high_staff = data.groupby("District") ["Total_Teachers"].sum().sort_values(ascending=False).reset_index()
top10_districts_high_staff.head(10)

       District  Total_Teachers
0      MACHAKOS           16832
1       MAKUENI           16043
2         KITUI           12122
3       NAIROBI           11134
4  MERU CENTRAL            8902
5        NAKURU            8327
6    MERU NORTH            7629
7        MWINGI            7425
8   UASIN GISHU            7120
9       BUNGOMA            6647

In [12]:
#checking missing values
data['PupilTeach'].isna().sum(), (data["PupilTeach"] <=0).sum()
data2 = data[data["PupilTeach"] > 0].copy()

In [13]:
#	Districts or locations with the highest average student-to-teacher ratios (PupilTeach).
district_avg_ratio = data2.groupby("District") ["PupilTeach"].mean().round(2).sort_values(ascending=True).reset_index()
district_avg_ratio.columns = ["District", "Average Student-to-Teacher Ratio"]
district_avg_ratio.head(10)

       District  Average Student-to-Teacher Ratio
0    MERU SOUTH                             20.37
1       NAIROBI                             22.10
2     KIRINYAGA                             23.57
3  MERU CENTRAL                             23.85
4       THARAKA                             24.90
5         THIKA                             25.26
6         NYERI                             25.72
7       MOMBASA                             25.80
8       MURANGA                             25.80
9       BARINGO                             25.85

In [14]:
district_avg_ratio.tail(10)

         District  Average Student-to-Teacher Ratio
61  BUTERE/MUMIAS                             46.34
62         KILIFI                             47.05
63          NAROK                             47.78
64     WEST POKOT                             48.06
65         MOYALE                             48.21
66     TRANS MARA                             50.02
67          KWALE                             50.68
68        TURKANA                             53.83
69          IJARA                             56.49
70        MANDERA                             61.75

In [15]:
location_avg_ratio = data2.groupby(["Location", "Province"]) ["PupilTeach"].mean().round(2).sort_values(ascending=False).reset_index()
location_avg_ratio.columns = ["Location", "Province", "Average Student-to-Teacher Ratio"]
location_avg_ratio.head()

             Location       Province  Average Student-to-Teacher Ratio
0         N.W. KISUMU         NYANZA                            610.00
1             NCHOORO        EASTERN                            194.35
2          SHAURIMOYO        NAIROBI                            191.40
3              DARWED  NORTH EASTERN                            165.20
4  NORTH EAST NYAKACH         NYANZA                            160.00

In [16]:
#Districts with highest teacher shortages 
#Filter out invalid rows
data2 = data2[(data2["TotalEnrol"] > 0) & (data2["Total_Teachers"] > 0)].copy()

#Calculate teachers needed based on 40:1 ratio
teachers_required = (data2["TotalEnrol"] /40).round().astype(int)
teachers_required.head()

# Calculate teacher shortages with no negative shortage.
data2["Teacher_Shortage"] = (teachers_required - data2["Total_Teachers"]).clip(lower=0)

#Teacher shortage by district
district_teacher_shortage = data2.groupby("District") ["Teacher_Shortage"].sum().round().sort_values(ascending=False).reset_index()
district_teacher_shortage.columns = ["District","Teachers_Needed"]
district_teacher_shortage.head()

     District  Teachers_Needed
0     BUNGOMA             4191
1  MERU NORTH             3922
2     NAIROBI             3826
3      NAKURU             3790
4    MACHAKOS             3439

In [17]:
#schools with low or zero teaching staff.
data2=data2.rename(columns={"Name_of_Sc": "School_Name"})

data2["low_teachers"] = data2["Total_Teachers"] <=10
data2.head()

#school name with low staff
schools_with_low_staff = data2.groupby("School_Name")["Total_Teachers"].count().sort_values(ascending=False).reset_index()
schools_with_low_staff.columns = ['School_Name', 'Total_Teachers']
#schools_with_low_staff.head()

In [18]:
data2.columns

Index(['FID', 'School_Name', 'Level_', 'Status', 'SchSponsor', 'Type1',
       'Type2', 'Type3', 'PupilTeach', 'ClassrmRat', 'ToiletRati',
       'No_Classrm', 'BoysToilet', 'GirlsToilet', 'TeachersTo', 'TotalToile',
       'TotalBoys', 'TotalGirls', 'TotalEnrol', 'GO_KTSC_M', 'GOK_TSC_F',
       'authorityM', 'authorityF', 'PTA_BOG_M', 'PTA_BOG_F', 'OthersM',
       'OthersF', 'NoTeaching', 'NonTeachin', 'Province', 'District',
       'Division', 'Location', 'Costituenc', 'Latitude', 'Longitude',
       'Total_Teachers', 'Teacher_Shortage', 'low_teachers'],
      dtype='object')

In [19]:
selected_columns = data2[['School_Name','GO_KTSC_M', 'GOK_TSC_F', 'PTA_BOG_M', 'PTA_BOG_F', 'Total_Teachers', 'OthersM',
       'OthersF', 'authorityM', 'authorityF']]   
selected_columns.head()

,School_Name,GO_KTSC_M,GOK_TSC_F,PTA_BOG_M,PTA_BOG_F,Total_Teachers,OthersM,OthersF,authorityM,authorityF
0,CHEBIREBEI PRI,2.0,1.0,0.0,0.0,9,0.0,0.0,0.0,0.0
1,WASEGES PRI,6.0,0.0,0.0,0.0,6,0.0,0.0,0.0,0.0
2,KIRIBOT PRI,5.0,0.0,0.0,0.0,15,0.0,0.0,0.0,0.0
3,KABUSWO PRI SCH,7.0,1.0,0.0,0.0,13,0.0,0.0,0.0,0.0
4,VONDENI PRI SCHOOL,4.0,3.0,1.0,0.0,10,0.0,0.0,0.0,0.0

In [29]:
# districts with highest number of female teachers than male.
data2=data2.rename(columns={"GO_KTSC_M": "TSC_Male", "GOK_TSC_F": "TSC_Female"})

data2["Total_Female_Teachers"] = data2["TSC_Female"] + data2["PTA_BOG_F"]
data2["Total_Male_Teachers"] = data2["TSC_Male"] + data2["PTA_BOG_M"]

data3 = data2[["Total_Male_Teachers", "Total_Female_Teachers"]].groupby(data2["District"]).sum()
data3.head()

          Total_Male_Teachers  Total_Female_Teachers
District
BARINGO                1585.0                 1466.0
BOMET                  1884.0                  907.0
BONDO                  1447.0                  802.0
BUNGOMA                3863.0                 3539.0
BURETI                 1230.0                  954.0